version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/hello-world-flask-app

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/start_python_app.sh
      timeout: 300
      runas: root